name = "outscore-api"
main = "src/index.ts"
compatibility_date = "2025-03-07"
compatibility_flags = ["nodejs_compat"]

# R2 bucket for storing match data
[[r2_buckets]]
binding = "FOOTBALL_CACHE"
bucket_name = "outscore-match-data"
preview_bucket_name = "outscore-match-data-dev"

# Environment variables
[vars]
FOOTBALL_API_URL = "https://api-football-v1.p.rapidapi.com/v3"


# Enable observability
[observability]
enabled = true
head_sampling_rate = 1