name = "outscore-api"
main = "src/index.ts"
compatibility_date = "2025-03-07"
compatibility_flags = ["nodejs_compat"]

# R2 bucket for storing match data
[[r2_buckets]]
binding = "FOOTBALL_CACHE"
bucket_name = "outscore-match-data"
preview_bucket_name = "outscore-match-data-dev"

# Environment variables
[vars]
FOOTBALL_API_URL = "https://api-football-v1.p.rapidapi.com/v3"

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = "OUTSCORE_RATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "1001"

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 100, period = 60 }


# Enable observability
[observability]
enabled = true
head_sampling_rate = 1